docs(secrets): known issues for secrets and spring cloud config
armory/docs pull request #1443
Opened 2022-06-02 17:52 UTC by nemesisOsorio

2022-06-06 18:44 UTC, sergio-quintero approved these changes

2022-06-14 17:45 UTC, aimeeu requested changes

2022-06-14 17:45 UTC, aimeeu commented on content/en/includes/known-issues/ki-secrets-and-spring-cloud.md
> +using [Secrets](https://docs.armory.io/armory-enterprise/armory-admin/secrets/)
```suggestion
using [Secrets]({{< ref "armory-enterprise/armory-admin/secrets" >}})
```

2022-06-14 17:45 UTC, aimeeu commented on content/en/includes/known-issues/ki-secrets-and-spring-cloud.md
> +will not be resolved when spring cloud tries to refresh.
```suggestion
are not resolved when Spring Cloud tries to refresh.
```

2022-06-14 17:45 UTC, aimeeu commented on content/en/includes/known-issues/ki-secrets-and-spring-cloud.md
> +Do not use secrets for properties that are annotated with `@RefreshScope`
```suggestion
Do not use secrets for properties that are annotated with `@RefreshScope`.
```

2022-06-14 17:53 UTC, merged