fix(comp-matrix): Terraform version support fixes
armory/docs pull request #1633
Opened 2022-10-11 22:58 UTC by tsonny

Resolves Jira: [https://armory.atlassian.net/browse/BOB-30827?focusedCommentId=91833]

2022-10-12 15:07 UTC, mknous requested changes
From what I can see, the chart shows 0.11.10 - 0.11.14 needs to be 2.27.0 and earlier, not 2.28.0 and earlier.

2022-10-13 14:07 UTC, jasonmcintosh approved these changes

2022-10-13 14:07 UTC, jasonmcintosh commented on content/en/armory-enterprise/feature-status/armory-enterprise-matrix/_index.md
> +| 0.13.4 - 0.13.5    | 2.24.0 - 2.28.0           |      |
Sorta minor, but probably should match on language.  E.g. "All supported versions" for all the columns vs. mentioning 2.24 and such?  

Another option:

| CDSH Version | Terraform Supported Versions | Notes |
| ----- | ----- | ---- | 
| 2.26 |  0.11, 0.12, 0.13, 0.14, 0.15, 1.0 |
| 2.27 |  0.11, 0.12, 0.13, 0.14, 0.15, 1.0, 1.1, 1.2 |
| 2.28 |  0.12, 0.13, 0.14, 0.15,  1.0, 1.1, 1.2 | 0.12 was removed initially and added back in 2.28.1 |
<td colspan=2>Note that not all patch versions are included, based upon request/time of release of available versions

2022-10-14 17:40 UTC, jasonmcintosh approved these changes

2022-10-14 17:40 UTC, merged