docs(plugin): added cats plugin documentation
armory/docs pull request #2244
Opened 2023-11-30 00:19 UTC by OscarMichelH

2023-11-30 16:51 UTC, kyledmitchell commented on content/en/includes/plugins/cats/compat-matrix.md
We do not have a 2.29 version officially.  1.29 and 1.30 are both wrapped up in 2.30 so we need to remove the 2.29 line and maybe put both 1.29 and 1.30 in the same box on the 2.30 line.

2023-11-30 16:56 UTC, kyledmitchell commented on content/en/plugins/cache-agents-on-event/_index.md
The plugin should called AWS Event Cache Plugin.  "Cache Agents on Event Plugin" is not correct.  We should update all references to that on this page on the plugin table on Plugins landing page.

In Description change "The rate limit handling plugin enhances." --> "The plugin enhances"

2023-11-30 17:01 UTC, kyledmitchell requested changes
See comments about changing all references to the name, updating the compat. matrix and potentially adding additional install pages/options similar to how we did for GitHub Integration plugin

2023-11-30 17:01 UTC, kyledmitchell commented on content/en/plugins/cache-agents-on-event/_index.md
> +## Installation paths
Shouldn't we include an install option for Halyard?  Is the installation the same for Armory CD and Spinnaker OSS?

Note how the GitHub Integration Plugin has 3 separate install pages/paths for the different install types
https://deploy-preview-2244--armory-docs.netlify.app/plugins/github-integration/

2023-11-30 22:42 UTC, aimeeu commented on content/en/plugins/cache-agents-on-event/_index.md
> +## Installation paths
I added a stub for Halyard, but I'm not sure of the exact YAML. I'll ask Oscar.

2023-12-01 05:24 UTC, OscarMichelH commented on content/en/plugins/cache-agents-on-event/_index.md
> +## Installation paths
I completed Halyard section with remaining configs 😃

2023-12-12 19:14 UTC, aimeeu approved these changes

2023-12-12 19:15 UTC, aimeeu commented
Kyle approved via Slack

2023-12-12 19:15 UTC, merged