docs(demo): add demo page
armory/docs pull request #466
Opened 2021-02-23 00:22 UTC by brian-armory

Resolves issue: [DOC-317]

2021-02-23 00:36 UTC, brian-armory commented on content/en/docs/Overview/demo-armory.md
> +  * 16 GB of memory
extracted these from t3.xlarge specs

2021-03-31 19:48 UTC, aimeeu requested changes

2021-03-31 19:48 UTC, aimeeu commented on content/en/docs/Overview/demo/_index.md
> +Minnaker uses [K3s](https://k3s.io/) as the kubernetes server. If you already have a kubernetes cluster for testing you can skip to [Install Minnaker](/docs/overview/demo/install-demo#install-minnake
```suggestion
Minnaker uses [K3s](https://k3s.io/) as the Kubernetes server. If you already have a Kubernetes cluster for testing, you can skip to [Install Minnaker]({{< ref "install-demo#install-minnaker" >}}).
```

2021-03-31 19:48 UTC, aimeeu commented on content/en/docs/Overview/demo/install-demo.md
> +    The commands above declaratively deploy Armory using git clone, [kustomize](https://kustomize.io/), and [Armory Operator](/docs/installation/operator/).  The entire configuration is gitops enable
```suggestion
    The commands above declaratively deploy Armory using `git clone`, [Kustomize](https://kustomize.io/), and [Armory Operator]({{< ref "operator" >}}).  The entire configuration is GitOps enabled for you so you can ‘git push’ your configurations to your own source control. 
```

2021-04-13 17:58 UTC, alexfornuto commented
The PR is now dependent on #449, as it links to pages created there. Once #449 is merged I will rebase this PR and submit it for review.

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +Armory Enteprise for Spinnaker is an superset of Spinnaker, which itself is a collection of microservices working in concert to create a single continuous delivery / deployment service.
```suggestion
Armory Enteprise for Spinnaker is a superset of Spinnaker, which itself is a collection of microservices working in concert to create a single continuous delivery / deployment service.
```

\<nitpick /\>

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +What is included in Armory Easy Poc?
> Armory Easy Poc?

Should this be Minnaker?

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +- Infrastructure as Code (IaC) using gitops and Terraform
`leveraging` perhaps conveys better intent here. `gitops` isn't a tool so much as its a certain way of using IaC manifests in some kind of deployment

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +- Declarative Spinnaker Application and Pipelines for (Pipelines as Code)
Should Application be plural as well?

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +- Automatic EKS Provisioning through gitops
What does this mean exactly, does the demo provision EKS clusters?

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +- Armory Agent for Kubernetes (delegate for kubernetes)
Should we link to agent documentation here?

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +- Enterprise Armory Platform powered by Spinnaker
Could you help me understand what is meant with this feature?

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +Minnaker uses [K3s](https://k3s.io/) as the Kubernetes server. If you already have a Kubernetes cluster for testing, you can skip to [Install Minnaker]({{< ref "install-demo#install-minnaker" >}}).
```suggestion
Minnaker uses [K3s](https://k3s.io/) as the Kubernetes implementation. If you already have a Kubernetes cluster for testing, you can skip to [Install Minnaker]({{< ref "install-demo#install-minnaker" >}}).
```

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +If deploying to an EC2 instance, we suggest using the t2.xlarge tier.
If we're suggesting a default instance size can we make it `t3a.xlarge`? It is the newest and cheapest of the `t` offerings from Amazon, and [comparable in traditional specs](https://aws.amazon.com/ec2/pricing/on-demand/) to the `t2` class instances.

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +If deploying to an EC2 instance, we suggest using the t2.xlarge tier.
```suggestion
If deploying to an EC2 instance, we suggest using a t3a.xlarge instance.
```

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/_index.md
> +The Minnaker demo uses the Armory Operator to manage services, and Kustomize to manage configuration files. If you're unfamiliar with either, check out the following docs before you being:
```suggestion
The Minnaker demo uses the Armory Operator to manage services, and Kustomize to manage configuration files. If you're unfamiliar with either, check out the following docs before you begin:
```

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/configure-integrations.md
> +1. In your Jenkins instance, create a new user and API token to authenticate to your Jenkins with. The Token will be stored as a Kubernetes secret, The user and host name will be stored in a yaml pat
Should we link to docs on how to create api users?

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/configure-integrations.md
> +1. From the Minnaker host CLI, temporarily set the user, token, and host name as envirnment variables:
```suggestion
1. From the Minnaker host CLI, temporarily set the user, token, and host name as environment variables:
```

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/configure-integrations.md
> +      # - accounts/canary/prometheus.yml        # TODO - need to add CONFIG STORE
Do we want to leave this here?

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/configure-integrations.md
> +1. Run `create-secrets.sh` in `spinsvc/secrets` to update the [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) with the new token.
```suggestion
1. Run `create-secrets.sh` in `spinsvc/secrets` to update the generated [Kubernetes Secret](https://kubernetes.io/docs/concepts/configuration/secret/) with the new token.
```

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/configure-integrations.md
> +   You can use watch kubectl get pods,spinsvc -n spinnaker from the host shell to monitor the status of the redeployment.
```suggestion
   You can use `watch kubectl get pods,spinsvc -n spinnaker` from the host shell to monitor the status of the redeployment.
```

To be consistent with other usages of this line

2021-04-14 18:33 UTC, dogonthehorizon commented on content/en/docs/Overview/demo/install-demo.md
> +1. The creating of namespaces, loading for CRD and Operator takes around 3 minutes to get Spinnaker fully installed with all services in a “Running” state. The script ends by running a `watch` comman
```suggestion
1. The creating of namespaces, loading for CRD and Operator takes around 3 minutes to get Spinnaker fully installed with all services in a “Running” state. The script ends by running a `watch` command to monitor the state of deployment. The environment is ready when the `spinnakerservice` object reads an "OK" status:
```

2021-04-14 19:36 UTC, alexfornuto commented on content/en/docs/Overview/demo/_index.md
> +Armory Enteprise for Spinnaker is an superset of Spinnaker, which itself is a collection of microservices working in concert to create a single continuous delivery / deployment service.
Not a nitpick, a legitimate copy edit. +1

2021-04-14 19:37 UTC, alexfornuto commented on content/en/docs/Overview/demo/_index.md
> +What is included in Armory Easy Poc?
Probably.

2021-04-14 19:48 UTC, alexfornuto commented on content/en/docs/Overview/demo/_index.md
> +- Automatic EKS Provisioning through gitops
I think this whole section is more about what Spinnaker and/or Armory Enterprise can do, not what this Minnaker demo provides. What do you think, should it be edited to be specific to what this guide demonstrates, or to explicitly be about what we _can_ offer?

CC @armory/docs-team for comment.

2021-04-14 20:00 UTC, alexfornuto commented on content/en/docs/Overview/demo/configure-integrations.md
> +      # - accounts/canary/prometheus.yml        # TODO - need to add CONFIG STORE
That's what's in the file when `kustomization.yml` is installed via the Minnaker script. The docs should reflect what the user sees, so if we want to remove this it should be from Minnaker first.

2021-04-14 20:01 UTC, alexfornuto commented on content/en/docs/Overview/demo/configure-integrations.md
> +   You can use watch kubectl get pods,spinsvc -n spinnaker from the host shell to monitor the status of the redeployment.
After moving it to include `watch`, big :+1:

2021-04-14 20:28 UTC, alexfornuto commented on content/en/docs/Overview/demo/configure-integrations.md
> +1. In your Jenkins instance, create a new user and API token to authenticate to your Jenkins with. The Token will be stored as a Kubernetes secret, The user and host name will be stored in a yaml pat
If I could find a good doc provided by Jenkins on this, I'd link to it. [This](https://www.jenkins.io/doc/book/system-administration/authenticating-scripted-clients/) is the closest I found, and I'm not sure it's useful for this application.

2021-11-19 22:05 UTC, closed without merging