docs(matrix): add system requirements doc DOC-350
armory/docs pull request #547
Opened 2021-04-07 17:03 UTC by brian-armory

Resolves Jira: [DOC-350]

2021-04-08 23:20 UTC, dogonthehorizon approved these changes
LGTM so far

2021-04-08 23:20 UTC, dogonthehorizon commented on content/en/docs/installation/system-requirements.md
> +You can use any modern browser to interact with the UI.
Do we want to put a limit on `modern` or is it generally understood what that means?

2021-04-08 23:20 UTC, dogonthehorizon commented on content/en/docs/installation/system-requirements.md
> +| MySQL      | MySQL 5.7 (or Aurora)    | Clouddriver, Front50, Orca                          |
```suggestion
| MySQL      | MySQL 5.7 (or Aurora)    | Clouddriver, Front50, Orca, Fiat, Echo                |                                                                                                                                                                                                                                                                                                                                                                                                       |
```

2021-04-08 23:20 UTC, dogonthehorizon commented on content/en/docs/installation/system-requirements.md
> +| PostgreSQL | PostgreSQL 10.0 or later | Clouddriver                                         |
```suggestion
| PostgreSQL | PostgreSQL 10.0 or later | Clouddriver, Front50, Orca, Fiat                     |                                                                                                                                                                                                                                                                                                                                                                                                       |
```

2021-04-19 16:54 UTC, aimeeu requested changes

2021-04-19 16:54 UTC, aimeeu commented on content/en/docs/installation/system-requirements.md
> +Armory Enterprise is a collection of services that run in a Kubernetes cluster. This section defines the versions that you can run Armory Enterprise on, not where you can deploy your applications. Fo
```suggestion
Armory Enterprise is a collection of services that run in a Kubernetes cluster. This section defines the versions that you can run Armory Enterprise on, not where you can deploy your applications. For information about what versions of Kubernetes you can deploy to, see the [Product Compatibility Matrix]({{< ref "armory-platform-matrix#container-as-a-service-platforms" >}}).
```
Since you specifically mention what versions of K8s you can deploy to, how about linking directly to the relevant section on the PCM page?

2021-06-02 19:31 UTC, dogonthehorizon approved these changes

2021-06-02 19:31 UTC, dogonthehorizon commented on content/en/docs/installation/system-requirements.md
> +* **Minimum version**: Some TBD version
1.16 as of this writing (lower bound for EKS)

2021-06-02 19:31 UTC, dogonthehorizon commented on content/en/docs/installation/system-requirements.md
> +* **Maximum version**: Some TBD version
1.20 as of this writing (upper bound for EKS)

I think long-term we should follow what EKS supports until we see customers overwhelmingly on another solution

2021-06-02 19:31 UTC, dogonthehorizon commented on content/en/docs/installation/system-requirements.md
> +To install Armory Enterprise, you can use either the Armory Operator (a Kubernetes operator) or Halyard. If you are installing Armory Enterprise for the first time, Armory recommends using the Armory
```suggestion
To install Armory Enterprise, you can use either the Armory Operator (a Kubernetes operator). Note that you must be able to apply Kubernetes manifests, either directly using `kubectl` commands from your machine or another method.
```

2021-06-09 15:27 UTC, dogonthehorizon approved these changes

2021-06-09 18:29 UTC, devorbitus commented on content/en/docs/installation/system-requirements.md
> +To install and manage Armory Enterprise, any actively maintained version of `kubectl` is supported unless you want to use the [Armory Kustomize Repo](https://github.com/armory/spinnaker-kustomize-pat
This may need rewording as the Armory Kustomize Repo uses kubectl as well but it is highly suggested to use that repo

2021-06-09 19:48 UTC, devorbitus approved these changes

2021-06-16 15:22 UTC, aimeeu commented on content/en/docs/installation/system-requirements.md
> +You install Armory Enterprise using the Armory Operator (a Kubernetes operator), which has the following requirements:
```suggestion
You install Armory Enterprise using the [Armory Operator]({{< ref "armory-operator" >}}) (a Kubernetes operator), which has the following requirements:
```

2021-06-16 15:31 UTC, aimeeu requested changes

2021-06-16 15:31 UTC, aimeeu commented on content/en/docs/installation/system-requirements.md
> +| PostgreSQL    | PostgreSQL 10.0 or later  | 2.24.0 or later | Clouddriver                          |
MySQL and PostgreSQL version are now parameters in config.toml.
mysql-version="5.7; AWS Aurora"
postgresql-version="10+"

2021-06-16 15:31 UTC, aimeeu commented on content/en/docs/installation/system-requirements.md
> +Armory recommends using MySQL or PostgreSQL as the backing store when possible for production instances of Spinnaker. For other services, use an external Redis instance for production instances of Sp
```suggestion
Armory recommends using MySQL or PostgreSQL as the backing store when possible for production instances of Spinnaker. For other services, use an external Redis instance for production instances of Armory Enterprise.
```

2021-06-16 15:31 UTC, aimeeu commented on content/en/docs/installation/system-requirements.md
> +To install and manage Armory Enterprise, Armory recommends using the [Armory Kustomize Repo](https://github.com/armory/spinnaker-kustomize-patches) and tailoring the Kustomize files to meet the requi
Rather than pointing to the repo, how about pointing to installation/armory-operator/op-config-kustomize.md ?

```suggestion
To install and manage Armory Enterprise, Armory recommends using the [Armory Operator with Kustomize]({{< ref "op-config-kustomize" >)}} and tailoring the Kustomize files to meet the requirements of your instance and environment. This installation method supports the following versions of `kubectl`: 1.16 to 1.19.
```

2021-06-16 15:31 UTC, aimeeu commented on content/en/docs/installation/system-requirements.md
> +It is possible to use the Operator to install Armory Enterprise without the Kustomize repo. In that case, any actively maintained version of `kubectl` is supported.
```suggestion
It is possible to use the Operator to [install Armory Enterprise without the Kustomize repo]({{< ref "op-config-manifest" >}}). In that case, any actively maintained version of `kubectl` is supported.
```

2021-06-16 17:37 UTC, brian-armory commented on content/en/docs/installation/system-requirements.md
> +| PostgreSQL    | PostgreSQL 10.0 or later  | 2.24.0 or later | Clouddriver                          |
Cool! Thanks for thinking ahead

2021-06-16 18:57 UTC, brian-armory commented
I addressed all of @aimeeu 's comments  @dogonthehorizon , so you can merge when you're ready

2021-06-16 22:10 UTC, dogonthehorizon approved these changes

2021-06-16 22:11 UTC, merged