docs(legal): add foot note and footer DOC-362
armory/docs pull request #563
Opened 2021-04-15 22:23 UTC by brian-armory

Resolves Jira: [DOC-362]

Footnote: https://s.armory.io/RBuYYk4w
Footnote part 2 + footer: https://s.armory.io/8LubblkP

2021-04-15 22:41 UTC, npetrell commented
Brian, Can we alter the language in the proprietary footnote? Instead of saying "Some or all" just say "Some" as clearly some of the features on the page are listed as OSS which wouldn't need a license. Some can mean all anyways. Otherwise, looks good to me.

2021-04-16 14:57 UTC, aimeeu requested changes
Few nits

2021-04-16 14:57 UTC, aimeeu commented on layouts/partials/footer.html
> +      <small class="text-white ml-1">Use of Armory products and features are subject to the
Small grammar nit: 
```suggestion
      <small class="text-white ml-1">Use of Armory products and features is subject to the
```
"Use" is singular...

2021-04-16 14:57 UTC, aimeeu commented on content/en/docs/armory-enterprise-matrix.md
>  ![OSS](/images/oss.svg) The feature or parts of it are available in Open Source Spinnaker.
open source Spinnaker vs Open Source Spinnaker ??

We seem to use "Open Source" and "open source" interchangeably. Google style guide lists it as "open source" in the [word list](https://developers.google.com/style/word-list#letter-o).

2021-04-16 15:28 UTC, brian-armory commented on content/en/docs/armory-enterprise-matrix.md
>  ![OSS](/images/oss.svg) The feature or parts of it are available in Open Source Spinnaker.
```suggestion
![OSS](/images/oss.svg) The feature or parts of it are available in open source Spinnaker.
```

2021-04-16 15:44 UTC, aimeeu approved these changes
lgtm - thanks!

2021-04-16 15:45 UTC, merged