Update(dinghy-enabled): Github Notifications
armory/docs pull request #625
Opened 2021-05-14 21:18 UTC by kinnonyee-armory

Documentation on Github notifications and issue that can occur
Suggest all parties look at this change

2021-05-14 21:36 UTC, aimeeu requested changes
Thanks Kinnon!

2021-05-14 21:36 UTC, aimeeu commented on content/en/docs/armory-admin/dinghy-enable.md
> +{{% alert title="New feature" %}}Github Notifications is a new feature in Armory 2.24.{{% /alert %}}
```suggestion
{{% alert title="New feature" %}}GitHub Notifications is a new feature in Armory 2.24.{{% /alert %}}
```

2021-05-14 21:36 UTC, aimeeu commented on content/en/docs/armory-admin/dinghy-enable.md
> +As a new feature in Armory's release of 2.24.x+, Dinghy can now provide more robust information to Github about executed pipeline changes.  This information appears as a comment in the PR.
```suggestion
As a new feature in Armory's release of 2.24.x+, Dinghy can now provide more robust information to GitHub about executed pipeline changes.  This information appears as a comment in the PR.  
```

2021-05-14 21:36 UTC, aimeeu commented on content/en/docs/armory-admin/dinghy-enable.md
> +*Currently, as of 2.24.1 and 2.25.0, [Github notifications are not supported with custom endpoints and should be disabled](https://support.armory.io/support?id=kb_article&sysparm_article=KB0010290).*
```suggestion
*Currently, as of 2.24.1 and 2.25.0, GitHub notifications are not supported with custom endpoints and should be disabled. See the [KB article](https://support.armory.io/support?id=kb_article&sysparm_article=KB0010290) for details.*
```

2021-05-14 21:36 UTC, aimeeu commented on content/en/docs/armory-admin/dinghy-enable.md
> +![Github Notifications](/images/armory-admin/dinghy-enable/dinghy-github-notifications.jpg)
```suggestion
![GitHub Notifications](/images/armory-admin/dinghy-enable/dinghy-github-notifications.jpg)
```

2021-05-17 14:34 UTC, dogonthehorizon approved these changes

2021-05-17 15:34 UTC, aimeeu approved these changes

2021-05-17 15:34 UTC, merged

2021-05-17 15:34 UTC, kinnonyee-armory commented
I'm good with any and all of your changes Aimee :) Thanks again!