feature(docs):operator
armory/docs pull request #630
Opened 2021-05-19 13:57 UTC by natereid72

removed references to beta, removed link to halyard config for git/repo artifact, added operator config for git/repo artifact.

Resolves GitHub issue: <link to GH issue>

Resolves Jira: [JIRAPROJECT-123]

2021-05-20 18:33 UTC, aimeeu requested changes
Thanks for submitting this PR!

2021-05-20 18:33 UTC, aimeeu commented on content/en/docs/spinnaker-user-guides/kustomize-manifests.md
> +Kustomize requires the git/repo artifact type.
```suggestion
Kustomize requires the `git/repo` artifact type.
```

2021-05-20 18:33 UTC, aimeeu commented on content/en/docs/spinnaker-user-guides/kustomize-manifests.md
> +apiVersion: spinnaker.armory.io/v1alpha2
```suggestion
apiVersion: spinnaker.armory.io/{{< param operator-extended-crd-version >}}
```

`param operator-extended-crd-version` is defined in config.toml so we don't have to hardcode `v1alpha2`

2021-05-21 14:19 UTC, natereid72 reviewed
ok

2021-05-21 14:24 UTC, natereid72 reviewed
ok

2021-05-21 15:46 UTC, aimeeu approved these changes

2021-05-21 15:46 UTC, merged