docs(aurora): fix permission scopes
armory/docs pull request #921
Opened 2021-10-05 22:36 UTC by brian-armory

2021-10-13 19:53 UTC, aimeeu requested changes
few nits

2021-10-13 19:53 UTC, aimeeu commented on content/en/docs/installation/aurora-install.md
> +Use client credentials for authentication and authorization for Armory's hosted cloud services. For example, RNAs use these credentials to authenticate itself to Armory's hosted cloud services.
```suggestion
Use client credentials for authentication and authorization for Armory's hosted cloud services. Services such as RNAs use these credentials to authenticate to Armory's hosted cloud services.
```

2021-10-13 19:53 UTC, aimeeu commented on content/en/docs/installation/aurora-install.md
> +5. Create a credential for your RNAs. Use a descriptive name for the credential, such as `RNA for TV App K8s`
```suggestion
5. Create a credential for your RNA. Use a descriptive name for the credential, such as `RNA for TV App K8s`
```

2021-10-19 21:33 UTC, brian-armory commented
I'm going to close this since CDF is going to fix the pre-configured scope in the UI.

2021-10-19 21:33 UTC, closed without merging